version: 0.2
phases:
  pre_build:
    commands:
      - |
        yum install -y gettext
        # Helm installation
        curl --silent --location "https://get.helm.sh/helm-v3.9.2-linux-amd64.tar.gz" | tar xz -C /tmp
        mv /tmp/linux-amd64/helm /usr/local/bin
        chmod +x /usr/local/bin/helm
        # Terraform installation
        sudo yum install -y yum-utils
        sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
        sudo yum -y install terraform
        #eksctl & eksdemo installation
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        chmod +x /tmp/eksctl
        sudo mv /tmp/eksctl /usr/local/bin
        curl -sSL "https://github.com/awslabs/eksdemo/releases/download/v0.16.0/eksdemo_Linux_x86_64.tar.gz" | tar xz -C /tmp
        chmod +x /tmp/eksdemo
        mv /tmp/eksdemo /usr/local/bin          

  build:
    commands:
      - |
        set -x
        set -e

        aws configure set cli_pager ""

        ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
        BUCKET_NAME=${TFSTATE_BUCKET_NAME}
        BASE_DIR=${CODEBUILD_SRC_DIR}
        WORKSHOP_GIT_URL=${WORKSHOP_GIT_URL:-https://github.com/aws-samples/amazon-eks-security-immersion-day}
        WORKSHOP_GIT_BRANCH=${WORKSHOP_GIT_BRANCH:-mainline}
        IS_WS=${IS_WS:-false}
        GITEA_PASSWORD=${GITEA_PASSWORD}

        env | sort

        # clone and create CodeCommit repo
        git clone $WORKSHOP_GIT_URL $BASE_DIR || true
        cd $BASE_DIR
        git checkout $WORKSHOP_GIT_BRANCH
        cd -

        aws ssm put-parameter --name "eks-security-workshop-tf-backend-bucket" --type "String" --value "$BUCKET_NAME" --overwrite

        # This gives access to the EKS cluster in terraform

        # Common backend config

        ls -la $BASE_DIR/terraform/common

        echo "BUCKET_NAME=$BUCKET_NAME"

        cat << EOT > $BASE_DIR/terraform/common/backend_override.tf
        terraform {
          backend "s3" {
            bucket         = "$BUCKET_NAME"
            key            = "common/terraform.tfstate"
            region         = "$AWS_REGION"
          }
        }
        EOT

        GITEA_EXTERNAL_URL=$(aws ssm get-parameter --name "EksBlueprintGiteaExternalUrl" --query "Parameter.Value" --output text || true)
        for i in $(seq 1 60);
        do
          if [[ -z $GITEA_EXTERNAL_URL ]]; then
            sleep 10
            GITEA_EXTERNAL_URL=$(aws ssm get-parameter --name "EksBlueprintGiteaExternalUrl" --query "Parameter.Value" --output text || true)
            echo $GITEA_EXTERNAL_URL
          else
            break
          fi
        done

        if [[ $REQUESTED_ACTION == 'Delete' ]]; then


          eksdemo delete cluster eksworkshop-eksctl
          eksdemo delete kms-key eks-security-kms

          # Cleanup scripts
          DEBUG=1 TF_VAR_gitea_external_url=$GITEA_EXTERNAL_URL TF_VAR_gitea_password=$GITEA_PASSWORD $BASE_DIR/terraform/common/destroy.sh

        else

          # Project Creation
          DEBUG=1 TF_VAR_gitea_external_url=$GITEA_EXTERNAL_URL TF_VAR_gitea_password=$GITEA_PASSWORD $BASE_DIR/terraform/common/deploy.sh

          eksdemo create kms-key eks-security-kms
          eksdemo create cluster eksworkshop-eksctl --vpc-cidr 10.254.0.0/16 -N 3 --version 1.30 --encrypt-secrets eks-security-kms

        fi
  post_build:
    commands:
      # CODEBUILD_BUILD_SUCCEEDING = 1 Set to 0 if the build is failing, or 1 if the build is succeeding.
      - echo ">>> build status $CODEBUILD_BUILD_SUCCEEDING"
